version: '3'
services:
  sah-mvp-api:
    image: alexsuch/sah-mvp-api:$VERSION
    container_name: sah_mvp_api
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_JPA_SHOW_SQL=false
  sah-mvp-frontend:
    image: alexsuch/sah-mvp-frontend:$VERSION
    container_name: sah_mvp_frontend
  proxy:
    image: alexsuch/sah-mvp-proxy:$VERSION
    container_name: sah_mvp_proxy
    ports:
      - "80:80"
    depends_on:
      - sah-mvp-api
      - sah-mvp-frontend
  sah-mvp-initializer:
    image: alexsuch/sah-mvp-initializer:$VERSION
    container_name: sah_mvp_initializer
    environment:
      - API_URL=http://sah-mvp-api:8081/properties
      - FEED_URL=http://feeds.spotahome.com/trovit-Ireland.xml
      - LOCATION=trovit
    entrypoint: sh -c "dockerize -wait http://sah-mvp-api:8081/properties -timeout 600s && node index.js"
    depends_on:
      - sah-mvp-api
