version: '3'
services:
  mysql:
    image: mysql:8
    container_name: sah_mvp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sah-mvp
      - MYSQL_DATABASE=sah-mvp
    ports:
      - "3306:3306"
  sah-mvp-api:
    build:
      context: ./sah-mvp-api
      dockerfile: ./Dockerfile
    container_name: sah_mvp_api
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sah-mvp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=sah-mvp
    depends_on:
      - mysql
  sah-mvp-frontend:
    build:
      context: ./sah-mvp-frontend
      dockerfile: ./Dockerfile
    container_name: sah_mvp_frontend
  proxy:
    build:
      context: ./proxy
      dockerfile: ./Dockerfile
    container_name: sah_mvp_proxy
    ports:
      - "80:80"
    depends_on:
      - sah-mvp-api
      - sah-mvp-frontend
  sah-mvp-initializer:
    build:
      context: ./sah-mvp-initializer
      dockerfile: ./Dockerfile
    container_name: sah_mvp_initializer
    environment:
      - API_URL=http://sah-mvp-api:8081/properties
    entrypoint: sh -c "dockerize -wait http://sah-mvp-api:8081/properties -timeout 600s && node index.js"
    depends_on:
      - sah-mvp-api
